.\" This groff file is part of hx, a terminal hex editor.
.\"
.\" Copyright (c) 2016 Kevin Pors. See LICENSE for details.
.\"
.Dd November 04, 2016
.Dt HX 1 1
.Os hx 1.0.0

.Sh NAME
.Nm hx
.Nd tiny hex editor for virtual terminals.

.Sh SYNOPSIS
.Nm hx
.Op Fl g Ar num
.Op Fl o Ar num
.Op Fl v
.Op Fl h
FILE

.\" ===================================================================
.\" Section for description.
.\" ===================================================================
.Sh DESCRIPTION
The
.Nm
utility is a hex editor made for today's virtual terminals. It
uses vim-inspired key bindings to navigate and edit the binary contents
of a file.

The options included with the program are as follows:
.Bl -tag -width Ds
.It Fl g Ar grouping
specifies the grouping of bytes.
.It Fl o Ar octet_length
amount of octets to display per line.
.It Fl h
displays help and exits.
.It Fl v
displays version info and exits.
.El

.\" ===================================================================
.\" Section for the examples.
.\" ===================================================================
.Sh EXAMPLES
Open the hx binary in hex view, with default grouping of 4 bytes, and 16 octets per line.
.Pp
.Dl hx /usr/bin/hx
.Bd -literal -offset indent
000000000: 7f454c46 01010100 00000000 00000000  .ELF............
000000010: 02000300 01000000 4c8d0408 34000000  ........L...4...
000000020: b0dc0000 00000000 34002000 09002800  ........4. ...(.
.Ed

.Pp
Specifying a grouping of 2 bytes:
.Pp
.Dl hx -g 2 /usr/bin/hx
.Bd -literal -offset indent
000000000: 7f45 4c46 0101 0100 0000 0000 0000 0000  .ELF............
000000010: 0200 0300 0100 0000 4c8d 0408 3400 0000  ........L...4...
.Ed

.Pp
8 byte grouping, 24 octets per line:
.Pp
.Dl hx -g 8 -o 24 /usr/bin/hx
.Bd -literal -offset indent
000000000: 7f454c4601010100 0000000000000000 0200030001000000  .ELF....................
000000018: 4c8d040834000000 b0dc000000000000 3400200009002800  L...4...........4. ...(.
000000030: 2500220006000000 3400000034800408 3480040820010000  %.".....4...4...4... ...
000000048: 2001000005000000 0400000003000000 5401000054810408   ...............T...T...
.Ed

.\" ===================================================================
.\" Section key bindings.
.\" ===================================================================
.Sh KEY BINDINGS
To navigate in the editor, the following key bindings are made available:
.Pp
.Bl -item -compact -offset 2n
.It
CTRL+Q:    : quit immediately without saving.
.It
CTRL+S     : save file in-place.
.It
h / left   : move cursor one byte left in the buffer.
.It
l / right  : move cursor one byte right in the buffer.
.It
j / down   : move cursor one position up (= num_octets_per_line).
.It
k / up     : move cursor one position down (= num_octets_per_line).
.It
]          : increment the byte at the cursor position with 1.
.It
[          : decrement the byte at the cursor position with 1.
.It
x / delete : delete byte at current cursor position.
.It
r          : enable REPLACE mode.
.It
i          : enable INSERT mode (not functional yet).
.It
ESC        : enable COMMAND mode.
.El

.\" ===================================================================
.\" Bugs section.
.\" ===================================================================
.Sh BUGS
May very well be there. Pull requests and/or patches are welcome in any way.

.Nm
has not been tested well with huge files, so performance problems
may apply. Currently, a whole file is read into memory, meaning you are tied
to the amount of memory you currently have available. I developed the program
to alter binary executables, so really large files haven't been a problem for
me, yet.

.Nm
also does not use a library such as (n)curses to manipulate the terminal
screen, and relies solely on ANSI escape sequences. Therefore portability
may be an issue, but should work well on most modern terminal emulators.

.Sh COPYRIGHT

MIT License

Copyright (c) 2016 Kevin Pors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

.Sh SEE ALSO
.Xr xxd 1

.Sh AUTHORS

Original implementation by Kevin Pors <krpors@gmail.com>, with indirect help
of Salvatore Sanfilippo and his kilo editor <https://github.com/antirez/kilo>.

